[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Nilakkal Parking Backend"
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "numpy>=2.3.5",
    "pillow>=12.0.0"
]
